/* jti_dispatch.h — auto-generated by scripts/gen_dispatch.py  DO NOT EDIT */
#ifndef JTI_DISPATCH_H
#define JTI_DISPATCH_H

#include <stdint.h>
#include <protobuf-c/protobuf-c.h>

typedef enum {
    JTI_TREE_JTI  = 0,
    JTI_TREE_EVO  = 1,
    JTI_TREE_BOTH = 2,
} jti_tree_t;

typedef struct {
    uint32_t                         ext_num;
    jti_tree_t                       tree;
    const char                      *sensor_name;
    const ProtobufCMessageDescriptor *descriptor;
} jti_dispatch_entry_t;

extern const jti_dispatch_entry_t jti_dispatch[];
extern const int                  jti_dispatch_size;

/* Look up the dispatch entry for an extension number.
 * Returns NULL if not found. For conflicts, prefers JTI. */
const jti_dispatch_entry_t *jti_dispatch_lookup(uint32_t ext_num);

#endif /* JTI_DISPATCH_H */
