/* jti_dispatch.c — auto-generated by scripts/gen_dispatch.py  DO NOT EDIT */
#include "jti_dispatch.h"

#include "af_fab_stats.pb-c.h"
#include "alarmd-junos-state-fpm-render.pb-c.h"
#include "alarmd_oc.pb-c.h"
#include "ancpd_oc.pb-c.h"
#include "authd_cups.pb-c.h"
#include "authd_oc.pb-c.h"
#include "bbe-smg-cpd_pppoe_stats.pb-c.h"
#include "bbe-smg-cpd_sdb.pb-c.h"
#include "bbe-smgd-junos-state-soft-gre-render.pb-c.h"
#include "bbe-smgd_ancp_stats_oc.pb-c.h"
#include "bbe-smgd_pppoe_stats_oc.pb-c.h"
#include "bbe-smgd_rsmon_debug_oc.pb-c.h"
#include "bbe-smgd_rsmon_stats_oc.pb-c.h"
#include "bbe-smgd_smd_queue_stats_oc.pb-c.h"
#include "bbe-smgd_sub_mgmt_network_stats_oc.pb-c.h"
#include "bbe-stats-svcsd-telemetry.pb-c.h"
#include "bfdd-junos-openconfig-bfd-render.pb-c.h"
#include "bootzd-evo-openconfig-bootz-render.pb-c.h"
#include "chassisd-junos-state-chassis-render.pb-c.h"
#include "chassisd-junos-state-poe-render.pb-c.h"
#include "chassisd_oc.pb-c.h"
#include "clksyncd-junos-state-ptp-render.pb-c.h"
#include "clksyncd-junos-state-synce-render.pb-c.h"
#include "cmerror.pb-c.h"
#include "cmerror_data.pb-c.h"
#include "cosd_oc.pb-c.h"
#include "cpu_memory_utilization.pb-c.h"
#include "dcd_oc.pb-c.h"
#include "ddosd-junos-state-ddos-protection-render.pb-c.h"
#include "dot1xd-junos-openconfig-if-8021x-render.pb-c.h"
#include "dot1xd-junos-state-dot1x-render.pb-c.h"
#include "dot1xd_oc.pb-c.h"
#include "ehmd_comp_oc.pb-c.h"
#include "ehmd_oc.pb-c.h"
#include "ehmd_system_chassis_native.pb-c.h"
#include "ehmd_system_oc.pb-c.h"
#include "eventd-junos-state-system-syslog.pb-c.h"
#include "eventd.pb-c.h"
#include "fabric.pb-c.h"
#include "fabricHub-junos-state-fabric-render.pb-c.h"
#include "fabricHub_oc.pb-c.h"
#include "fabspoked-fchip-junos-openconfig-platform-render.pb-c.h"
#include "fabspoked-fchip-junos-state-sib-render.pb-c.h"
#include "fabspoked-pfe-junos-openconfig-platform-pipeline-counters-render.pb-c.h"
#include "fabspoked-pfe-junos-state-process-render.pb-c.h"
#include "fibtd-junos-state-anomalies-fib-render.pb-c.h"
#include "fibtd-telemetry_oc.pb-c.h"
#include "fibtd-telemetry_oc_programming_errors.pb-c.h"
#include "firewall.pb-c.h"
#include "fpc_environment.pb-c.h"
#include "fwstatsd_oc_df_sets_state.pb-c.h"
#include "fwstatsd_oc_evo_state.pb-c.h"
#include "fwstatsd_oc_ni.pb-c.h"
#include "fwstatsd_oc_ni_afts.pb-c.h"
#include "inline_jflow.pb-c.h"
#include "jdhcpd-junos-state-dhcp-security-render.pb-c.h"
#include "jdhcpd_oc.pb-c.h"
#include "jkdsd_cpu_oc.pb-c.h"
#include "jkdsd_oc.pb-c.h"
#include "jkdsd_system_cpu_oc.pb-c.h"
#include "jkdsd_system_memory_oc.pb-c.h"
#include "jkdsd_system_mount_points_oc.pb-c.h"
#include "jkhmd_oc.pb-c.h"
#include "jl2tpd_cups.pb-c.h"
#include "jl2tpd_oc.pb-c.h"
#include "jpppd_cups.pb-c.h"
#include "jpppd_oc.pb-c.h"
#include "jsd-junos-state-grpc.pb-c.h"
#include "jsd_health_oc.pb-c.h"
#include "jstatsd-junos-state-networking-render.pb-c.h"
#include "junos-xmlproxyd_junos-rsvp-interface.pb-c.h"
#include "junos-xmlproxyd_junos-rtg-task-memory.pb-c.h"
#include "kernel-ifstate-render.pb-c.h"
#include "l2ald-junos-state-l2-learning-render.pb-c.h"
#include "l2ald_oc.pb-c.h"
#include "l2ald_oc_intf.pb-c.h"
#include "l2cpd-junos-state-lldp-render.pb-c.h"
#include "l2cpd_oc.pb-c.h"
#include "l2cpd_stp_oc.pb-c.h"
#include "lacpd_oc.pb-c.h"
#include "ldp_lsp_ingress_stats.pb-c.h"
#include "ldp_lsp_transit_stats.pb-c.h"
#include "ldp_p2mp_lsp_branch_stats.pb-c.h"
#include "ldp_p2mp_lsp_stats.pb-c.h"
#include "ldp_p2mp_per_if_egress.pb-c.h"
#include "ldp_p2mp_per_if_ingress.pb-c.h"
#include "license-check-features-oc.pb-c.h"
#include "logical_port.pb-c.h"
#include "lsp_stats.pb-c.h"
#include "master-eventd-state-system-syslog.pb-c.h"
#include "master-eventd_oc.pb-c.h"
#include "mgmt-ethd_oc_component.pb-c.h"
#include "mgmt-ethd_oc_evo_intf_stats.pb-c.h"
#include "mib2d-junos-state-interfaces-render.pb-c.h"
#include "mib2d_arp_oc.pb-c.h"
#include "mib2d_native_evo_intf_state.pb-c.h"
#include "mib2d_nd6_oc.pb-c.h"
#include "mib2d_oc.pb-c.h"
#include "mib2d_oc_evo_intf_state.pb-c.h"
#include "na-grpcd_stats_oc.pb-c.h"
#include "npu_memory_utilization.pb-c.h"
#include "npu_utilization.pb-c.h"
#include "optics.pb-c.h"
#include "packet_capture.pb-c.h"
#include "packet_stats.pb-c.h"
#include "pfe-junos-slice-egr-qstats-render.pb-c.h"
#include "pfe-junos-state-flow-monitoring-render.pb-c.h"
#include "pfe_ddos_oc.pb-c.h"
#include "pfe_export_mon_oc.pb-c.h"
#include "pfe_ifl_family_v4_stats_oc.pb-c.h"
#include "pfe_ifl_family_v6_stats_oc.pb-c.h"
#include "pfe_ifl_oc.pb-c.h"
#include "pfe_iflset_qstats.pb-c.h"
#include "pfe_mpls_sr_te_bsid_openconfig_oc.pb-c.h"
#include "pfe_mpls_sr_te_ip_openconfig_oc.pb-c.h"
#include "pfe_mpls_sr_te_per_lsp_colored_ingress_oc.pb-c.h"
#include "pfe_mpls_sr_te_per_lsp_colored_transit_oc.pb-c.h"
#include "pfe_npu_resource.pb-c.h"
#include "pfe_page_drop_oc.pb-c.h"
#include "pfe_per_prefix_v4_stats.pb-c.h"
#include "pfe_per_prefix_v6_stats.pb-c.h"
#include "pfe_port_oc.pb-c.h"
#include "pfe_port_qstats_ext.pb-c.h"
#include "pfe_qos_egress_qstats.pb-c.h"
#include "pfe_qos_ingress_qstats.pb-c.h"
#include "pfe_srv6_isis_remote_locator_transit_stats.pb-c.h"
#include "pfe_srv6_srte_colored_per_path_ingress_stats.pb-c.h"
#include "pfe_srv6_srte_colored_per_policy_ingress_stats.pb-c.h"
#include "pfe_srv6_srte_uncolored_per_path_ingress_stats.pb-c.h"
#include "pfe_srv6_srte_uncolored_per_tunnel_ingress_stats.pb-c.h"
#include "pfed_oc.pb-c.h"
#include "pipeline_counters_drop_oc.pb-c.h"
#include "pipeline_counters_drop_queueing_block_oc.pb-c.h"
#include "pipeline_counters_packet_oc.pb-c.h"
#include "pipeline_counters_packet_queueing_block_oc.pb-c.h"
#include "pkid-evo-openconfig-certz-render.pb-c.h"
#include "port.pb-c.h"
#include "port_exp.pb-c.h"
#include "qmon.pb-c.h"
#include "rpd-junos-openconfig-ospfv2-render.pb-c.h"
#include "rpd_bgp_junos_diagnostics.pb-c.h"
#include "rpd_bgp_junos_route_validation.pb-c.h"
#include "rpd_bgp_junos_state.pb-c.h"
#include "rpd_bgp_rib_oc.pb-c.h"
#include "rpd_evpn_instance_junos_state.pb-c.h"
#include "rpd_evpn_rib_oc.pb-c.h"
#include "rpd_gribi_stats_oc.pb-c.h"
#include "rpd_if_ipv6_ra_oc.pb-c.h"
#include "rpd_igmp_oc.pb-c.h"
#include "rpd_ipv6_ra_oc.pb-c.h"
#include "rpd_isis_oc.pb-c.h"
#include "rpd_ldp_oc.pb-c.h"
#include "rpd_ni_bgp_oc.pb-c.h"
#include "rpd_ni_oc.pb-c.h"
#include "rpd_pim_oc.pb-c.h"
#include "rpd_policy_oc.pb-c.h"
#include "rpd_routing_tables_junos_state.pb-c.h"
#include "rpd_rsvp_oc.pb-c.h"
#include "rpd_srte_policy_oc.pb-c.h"
#include "rpd_srv6_junos_state.pb-c.h"
#include "rpd_static_routing_junos_state.pb-c.h"
#include "rpd_te_oc.pb-c.h"
#include "saegw-upad_oc.pb-c.h"
#include "smid_oc.pb-c.h"
#include "smid_vc_oc.pb-c.h"
#include "spu_cpu_util.pb-c.h"
#include "spu_flow_stats.pb-c.h"
#include "sr_stats_per_if_egress.pb-c.h"
#include "sr_stats_per_if_ingress.pb-c.h"
#include "sr_stats_per_sid.pb-c.h"
#include "sr_stats_per_sid_egress.pb-c.h"
#include "sr_te_bsid_stats.pb-c.h"
#include "sr_te_ingress_tunnel_stats.pb-c.h"
#include "sr_te_ip_stats.pb-c.h"
#include "sr_te_per_lsp_ingress_stats.pb-c.h"
#include "sr_te_per_lsp_transit_stats.pb-c.h"
#include "sr_te_transit_tunnel_stats.pb-c.h"
#include "svcsd_sflow_oc.pb-c.h"
#include "svcsd_sflow_openconfig.pb-c.h"
#include "sysd-evo-openconfig-system-render.pb-c.h"
#include "sysd-junos-openconfig-system-render.pb-c.h"
#include "transceiver.pb-c.h"
#include "vrrpd_oc.pb-c.h"
#include "xmlproxyd-junos-commit-entries-render.pb-c.h"
#include "xmlproxyd_show_local_interface_OC.pb-c.h"

extern const ProtobufCMessageDescriptor acl_fwstatsd_evolved_251__descriptor;
extern const ProtobufCMessageDescriptor af_fab_stats__descriptor;
extern const ProtobufCMessageDescriptor arp_information_mib_arp__descriptor;
extern const ProtobufCMessageDescriptor bfd_242__descriptor;
extern const ProtobufCMessageDescriptor cmerror__descriptor;
extern const ProtobufCMessageDescriptor cmerror_data__descriptor;
extern const ProtobufCMessageDescriptor components__descriptor;
extern const ProtobufCMessageDescriptor components_debug__descriptor;
extern const ProtobufCMessageDescriptor components_fab__descriptor;
extern const ProtobufCMessageDescriptor components_fpc_240__descriptor;
extern const ProtobufCMessageDescriptor components_pipeline_counters_drop_281__descriptor;
extern const ProtobufCMessageDescriptor components_pipeline_counters_packet_280__descriptor;
extern const ProtobufCMessageDescriptor components_queueing_block_drop_299__descriptor;
extern const ProtobufCMessageDescriptor components_queueing_block_packet_298__descriptor;
extern const ProtobufCMessageDescriptor components_re_215__descriptor;
extern const ProtobufCMessageDescriptor components_re_333__descriptor;
extern const ProtobufCMessageDescriptor components_telemetry__descriptor;
extern const ProtobufCMessageDescriptor cpu_memory_utilization__descriptor;
extern const ProtobufCMessageDescriptor ddos_stats__descriptor;
extern const ProtobufCMessageDescriptor debug_queue_stats__descriptor;
extern const ProtobufCMessageDescriptor debug_rsmon_debug__descriptor;
extern const ProtobufCMessageDescriptor defined_sets_fwstatsd_evolved_df_sets_335__descriptor;
extern const ProtobufCMessageDescriptor diagnostics_bgp_diagnostics_347__descriptor;
extern const ProtobufCMessageDescriptor fabric_message__descriptor;
extern const ProtobufCMessageDescriptor firewall__descriptor;
extern const ProtobufCMessageDescriptor g_fpc_environment__descriptor;
extern const ProtobufCMessageDescriptor gribi_statistics_gribi_stats_229__descriptor;
extern const ProtobufCMessageDescriptor inline_jflow__descriptor;
extern const ProtobufCMessageDescriptor interfaces_if_ipv6_ra_305__descriptor;
extern const ProtobufCMessageDescriptor interfaces_interface__descriptor;
extern const ProtobufCMessageDescriptor interfaces_l2al_interface__descriptor;
extern const ProtobufCMessageDescriptor interfaces_local_interface__descriptor;
extern const ProtobufCMessageDescriptor interfaces_mgmt__descriptor;
extern const ProtobufCMessageDescriptor interfaces_mib__descriptor;
extern const ProtobufCMessageDescriptor interfaces_mib_evolved__descriptor;
extern const ProtobufCMessageDescriptor interfaces_pfe_ifl__descriptor;
extern const ProtobufCMessageDescriptor interfaces_pfe_ifl_family_v4__descriptor;
extern const ProtobufCMessageDescriptor interfaces_pfe_ifl_family_v6__descriptor;
extern const ProtobufCMessageDescriptor interfaces_pfe_port__descriptor;
extern const ProtobufCMessageDescriptor interfaces_pfe_port_qstats__descriptor;
extern const ProtobufCMessageDescriptor interfaces_pnac_261__descriptor;
extern const ProtobufCMessageDescriptor interfaces_vrrp__descriptor;
extern const ProtobufCMessageDescriptor ipv6_ra_ipv6_ra__descriptor;
extern const ProtobufCMessageDescriptor junos_228__descriptor;
extern const ProtobufCMessageDescriptor junos_254__descriptor;
extern const ProtobufCMessageDescriptor junos_ancp__descriptor;
extern const ProtobufCMessageDescriptor junos_ancp_stats__descriptor;
extern const ProtobufCMessageDescriptor junos_authentication_274__descriptor;
extern const ProtobufCMessageDescriptor junos_authentication__descriptor;
extern const ProtobufCMessageDescriptor junos_dhcp__descriptor;
extern const ProtobufCMessageDescriptor junos_events__descriptor;
extern const ProtobufCMessageDescriptor junos_kernel_health__descriptor;
extern const ProtobufCMessageDescriptor junos_kernel_ifstate__descriptor;
extern const ProtobufCMessageDescriptor junos_l2tp_276__descriptor;
extern const ProtobufCMessageDescriptor junos_l2tp__descriptor;
extern const ProtobufCMessageDescriptor junos_network_stats__descriptor;
extern const ProtobufCMessageDescriptor junos_pfe__descriptor;
extern const ProtobufCMessageDescriptor junos_pfe_export_mon_stats__descriptor;
extern const ProtobufCMessageDescriptor junos_pfe_iflset_234__descriptor;
extern const ProtobufCMessageDescriptor junos_pfe_npu__descriptor;
extern const ProtobufCMessageDescriptor junos_pfe_packet_capture__descriptor;
extern const ProtobufCMessageDescriptor junos_pfe_slice_egr_qstats_243__descriptor;
extern const ProtobufCMessageDescriptor junos_pfe_spu_cpu__descriptor;
extern const ProtobufCMessageDescriptor junos_pfe_spu_flow__descriptor;
extern const ProtobufCMessageDescriptor junos_ppp_277__descriptor;
extern const ProtobufCMessageDescriptor junos_ppp__descriptor;
extern const ProtobufCMessageDescriptor junos_pppoe_stats_273__descriptor;
extern const ProtobufCMessageDescriptor junos_pppoe_stats__descriptor;
extern const ProtobufCMessageDescriptor junos_rsmon_stats__descriptor;
extern const ProtobufCMessageDescriptor junos_rsvp_interface__descriptor;
extern const ProtobufCMessageDescriptor junos_saegw__descriptor;
extern const ProtobufCMessageDescriptor junos_smi_272__descriptor;
extern const ProtobufCMessageDescriptor junos_smi__descriptor;
extern const ProtobufCMessageDescriptor junos_smi_vc_314__descriptor;
extern const ProtobufCMessageDescriptor junos_subscribers_312__descriptor;
extern const ProtobufCMessageDescriptor junos_task_memory__descriptor;
extern const ProtobufCMessageDescriptor junos_telemetry__descriptor;
extern const ProtobufCMessageDescriptor lacp_lacp__descriptor;
extern const ProtobufCMessageDescriptor ldp_lsp_ingress_stats__descriptor;
extern const ProtobufCMessageDescriptor ldp_lsp_transit_stats__descriptor;
extern const ProtobufCMessageDescriptor ldp_p2mp_lsp_branch_stats__descriptor;
extern const ProtobufCMessageDescriptor ldp_p2mp_lsp_stats__descriptor;
extern const ProtobufCMessageDescriptor ldp_p2mp_per_if_egress__descriptor;
extern const ProtobufCMessageDescriptor ldp_p2mp_per_if_ingress__descriptor;
extern const ProtobufCMessageDescriptor lldp_l2cp__descriptor;
extern const ProtobufCMessageDescriptor logical_port__descriptor;
extern const ProtobufCMessageDescriptor lsp_stats__descriptor;
extern const ProtobufCMessageDescriptor macsec_macsec__descriptor;
extern const ProtobufCMessageDescriptor mpls__sr_te_per_lsp_ingress_stats__descriptor;
extern const ProtobufCMessageDescriptor mpls__sr_te_per_lsp_transit_stats__descriptor;
extern const ProtobufCMessageDescriptor nd6_information_mib_nd6__descriptor;
extern const ProtobufCMessageDescriptor network_instances_318__descriptor;
extern const ProtobufCMessageDescriptor network_instances__descriptor;
extern const ProtobufCMessageDescriptor network_instances__igmp_262__descriptor;
extern const ProtobufCMessageDescriptor network_instances__ospfv2_247__descriptor;
extern const ProtobufCMessageDescriptor network_instances__pim__descriptor;
extern const ProtobufCMessageDescriptor network_instances__srte__descriptor;
extern const ProtobufCMessageDescriptor network_instances_bgp_rib__descriptor;
extern const ProtobufCMessageDescriptor network_instances_evpn_263__descriptor;
extern const ProtobufCMessageDescriptor network_instances_fwstatsd_evolved_ni_252__descriptor;
extern const ProtobufCMessageDescriptor network_instances_fwstatsd_evolved_ni_afts_321__descriptor;
extern const ProtobufCMessageDescriptor network_instances_isis__descriptor;
extern const ProtobufCMessageDescriptor network_instances_l2_network_instance__descriptor;
extern const ProtobufCMessageDescriptor network_instances_ldp__descriptor;
extern const ProtobufCMessageDescriptor network_instances_ni_226__descriptor;
extern const ProtobufCMessageDescriptor network_instances_ni_bgp__descriptor;
extern const ProtobufCMessageDescriptor network_instances_pfe_mpls_sr_te_bsid__descriptor;
extern const ProtobufCMessageDescriptor network_instances_pfe_mpls_sr_te_ip__descriptor;
extern const ProtobufCMessageDescriptor network_instances_pfe_mpls_sr_te_per_lsp_colored_ingress__descriptor;
extern const ProtobufCMessageDescriptor network_instances_pfe_mpls_sr_te_per_lsp_colored_transit__descriptor;
extern const ProtobufCMessageDescriptor network_instances_pfe_per_prefix_v4__descriptor;
extern const ProtobufCMessageDescriptor network_instances_pfe_per_prefix_v6__descriptor;
extern const ProtobufCMessageDescriptor network_instances_rsvp__descriptor;
extern const ProtobufCMessageDescriptor network_instances_te__descriptor;
extern const ProtobufCMessageDescriptor network_processor_memory_utilization__descriptor;
extern const ProtobufCMessageDescriptor network_processor_utilization__descriptor;
extern const ProtobufCMessageDescriptor optics__descriptor;
extern const ProtobufCMessageDescriptor packet_statistics__descriptor;
extern const ProtobufCMessageDescriptor port__descriptor;
extern const ProtobufCMessageDescriptor port_exp__descriptor;
extern const ProtobufCMessageDescriptor qos__descriptor;
extern const ProtobufCMessageDescriptor qos_pfe_egress_qstats__descriptor;
extern const ProtobufCMessageDescriptor qos_pfe_ingress_qstats_244__descriptor;
extern const ProtobufCMessageDescriptor queue_monitor__descriptor;
extern const ProtobufCMessageDescriptor routing_policy_policy_283__descriptor;
extern const ProtobufCMessageDescriptor sampling_253__descriptor;
extern const ProtobufCMessageDescriptor sr_stats_per_if_egress__descriptor;
extern const ProtobufCMessageDescriptor sr_stats_per_if_ingress__descriptor;
extern const ProtobufCMessageDescriptor sr_stats_per_sid__descriptor;
extern const ProtobufCMessageDescriptor sr_stats_per_sid_egress__descriptor;
extern const ProtobufCMessageDescriptor sr_te_bsid_stats__descriptor;
extern const ProtobufCMessageDescriptor sr_te_ingress_tunnel_stats__descriptor;
extern const ProtobufCMessageDescriptor sr_te_ip_stats__descriptor;
extern const ProtobufCMessageDescriptor sr_te_transit_tunnel_stats__descriptor;
extern const ProtobufCMessageDescriptor state_212__descriptor;
extern const ProtobufCMessageDescriptor state_235__descriptor;
extern const ProtobufCMessageDescriptor state_236__descriptor;
extern const ProtobufCMessageDescriptor state_279__descriptor;
extern const ProtobufCMessageDescriptor state_300__descriptor;
extern const ProtobufCMessageDescriptor state_307__descriptor;
extern const ProtobufCMessageDescriptor state_308__descriptor;
extern const ProtobufCMessageDescriptor state_331__descriptor;
extern const ProtobufCMessageDescriptor state_alarmd_native_fpm_309__descriptor;
extern const ProtobufCMessageDescriptor state_bgp_rv_291__descriptor;
extern const ProtobufCMessageDescriptor state_bgp_state_290__descriptor;
extern const ProtobufCMessageDescriptor state_chassis_246__descriptor;
extern const ProtobufCMessageDescriptor state_chassis_248__descriptor;
extern const ProtobufCMessageDescriptor state_commit_history_285__descriptor;
extern const ProtobufCMessageDescriptor state_dhcp_security_282__descriptor;
extern const ProtobufCMessageDescriptor state_dot1x_268__descriptor;
extern const ProtobufCMessageDescriptor state_events_278__descriptor;
extern const ProtobufCMessageDescriptor state_evpn_303__descriptor;
extern const ProtobufCMessageDescriptor state_fabric_path_296__descriptor;
extern const ProtobufCMessageDescriptor state_fabspoked_sib_310__descriptor;
extern const ProtobufCMessageDescriptor state_fpc_297__descriptor;
extern const ProtobufCMessageDescriptor state_l2_learning_306__descriptor;
extern const ProtobufCMessageDescriptor state_mib2d_native_288__descriptor;
extern const ProtobufCMessageDescriptor state_mib_249__descriptor;
extern const ProtobufCMessageDescriptor state_mist_238__descriptor;
extern const ProtobufCMessageDescriptor state_pfe_srv6_324__descriptor;
extern const ProtobufCMessageDescriptor state_pfe_srv6_col_per_path_ingress_326__descriptor;
extern const ProtobufCMessageDescriptor state_pfe_srv6_srte_325__descriptor;
extern const ProtobufCMessageDescriptor state_pfe_srv6_srte_uncolored_per_tun_ingress_327__descriptor;
extern const ProtobufCMessageDescriptor state_pfe_srv6_uncol_per_path_ingress_328__descriptor;
extern const ProtobufCMessageDescriptor state_routing_tables_state_304__descriptor;
extern const ProtobufCMessageDescriptor state_soft_gre_337__descriptor;
extern const ProtobufCMessageDescriptor state_srv6_state_322__descriptor;
extern const ProtobufCMessageDescriptor state_static_routing_state_315__descriptor;
extern const ProtobufCMessageDescriptor state_stats_286__descriptor;
extern const ProtobufCMessageDescriptor state_telemetry_293__descriptor;
extern const ProtobufCMessageDescriptor stp_stp_269__descriptor;
extern const ProtobufCMessageDescriptor system_259__descriptor;
extern const ProtobufCMessageDescriptor system_260__descriptor;
extern const ProtobufCMessageDescriptor system_319__descriptor;
extern const ProtobufCMessageDescriptor system_341__descriptor;
extern const ProtobufCMessageDescriptor system_alarm__descriptor;
extern const ProtobufCMessageDescriptor system_debug_232__descriptor;
extern const ProtobufCMessageDescriptor system_debug_266__descriptor;
extern const ProtobufCMessageDescriptor system_debug_267__descriptor;
extern const ProtobufCMessageDescriptor system_debug__descriptor;
extern const ProtobufCMessageDescriptor system_health__descriptor;
extern const ProtobufCMessageDescriptor system_license__descriptor;
extern const ProtobufCMessageDescriptor system_telemetry_213__descriptor;
extern const ProtobufCMessageDescriptor telemetry_system_stats__descriptor;
extern const ProtobufCMessageDescriptor transceiver_data__descriptor;

const jti_dispatch_entry_t jti_dispatch[] = {
    {     1, JTI_TREE_BOTH, "cpu_memory_util", &cpu_memory_utilization__descriptor },
    {     2, JTI_TREE_BOTH, "fabricMessageExt", &fabric_message__descriptor },
    {     3, JTI_TREE_BOTH, "interface", &port__descriptor },
    {     4, JTI_TREE_BOTH, "fpcEnvironmentExt", &g_fpc_environment__descriptor },
    {     5, JTI_TREE_BOTH, "lsp_statistics", &lsp_stats__descriptor },
    {     6, JTI_TREE_BOTH, "firewall", &firewall__descriptor },
    {     7, JTI_TREE_BOTH, "jnprLogicalInterfaceExt", &logical_port__descriptor },
    {     8, JTI_TREE_BOTH, "packet_statistics", &packet_statistics__descriptor },
    {     9, JTI_TREE_BOTH, "inline_jflow_stats", &inline_jflow__descriptor },
    {    10, JTI_TREE_BOTH, "optics", &optics__descriptor },
    {    11, JTI_TREE_BOTH, "npu_memory", &network_processor_memory_utilization__descriptor },
    {    12, JTI_TREE_BOTH, "npu_utilization", &network_processor_utilization__descriptor },
    {    15, JTI_TREE_BOTH, "qmon", &queue_monitor__descriptor },
    {    16, JTI_TREE_BOTH, "sr_stats_per_sid", &sr_stats_per_sid__descriptor },
    {    17, JTI_TREE_BOTH, "sr_stats_per_if_egress", &sr_stats_per_if_egress__descriptor },
    {    18, JTI_TREE_BOTH, "interface_exp", &port_exp__descriptor },
    {    19, JTI_TREE_BOTH, "sr_stats_per_if_ingress", &sr_stats_per_if_ingress__descriptor },
    {    20, JTI_TREE_BOTH, "cmerror", &cmerror__descriptor },
    {    21, JTI_TREE_BOTH, "cmerror_data", &cmerror_data__descriptor },
    {    24, JTI_TREE_BOTH, "sr_te_bsid_stats", &sr_te_bsid_stats__descriptor },
    {    25, JTI_TREE_BOTH, "sr_te_ip_stats", &sr_te_ip_stats__descriptor },
    {    26, JTI_TREE_BOTH, "sr_stats_per_sid_egress", &sr_stats_per_sid_egress__descriptor },
    {    28, JTI_TREE_BOTH, "sr_te_transit_tunnel_stats", &sr_te_transit_tunnel_stats__descriptor },
    {    29, JTI_TREE_BOTH, "sr_te_ingress_tunnel_stats", &sr_te_ingress_tunnel_stats__descriptor },
    {    32, JTI_TREE_BOTH, "junos_ancp", &junos_ancp__descriptor },
    {    33, JTI_TREE_BOTH, "junos_authentication", &junos_authentication__descriptor },
    {    34, JTI_TREE_BOTH, "junos_ancp_stats", &junos_ancp_stats__descriptor },
    {    35, JTI_TREE_BOTH, "junos_pppoe_stats", &junos_pppoe_stats__descriptor },
    {    36, JTI_TREE_BOTH, "debug_rsmon_debug", &debug_rsmon_debug__descriptor },
    {    37, JTI_TREE_BOTH, "junos_rsmon_stats", &junos_rsmon_stats__descriptor },
    {    38, JTI_TREE_BOTH, "debug_queue_stats", &debug_queue_stats__descriptor },
    {    39, JTI_TREE_BOTH, "junos_network_stats", &junos_network_stats__descriptor },
    {    40, JTI_TREE_JTI, "components", &components__descriptor },
    {    40, JTI_TREE_EVO, "af_fab_statistics", &af_fab_stats__descriptor },
    {    41, JTI_TREE_BOTH, "interfaces_interface", &interfaces_interface__descriptor },
    {    42, JTI_TREE_BOTH, "junos_events", &junos_events__descriptor },
    {    43, JTI_TREE_BOTH, "junos_dhcp", &junos_dhcp__descriptor },
    {    44, JTI_TREE_BOTH, "junos_l2tp", &junos_l2tp__descriptor },
    {    45, JTI_TREE_BOTH, "junos_ppp", &junos_ppp__descriptor },
    {    46, JTI_TREE_BOTH, "junos_rsvp_interface", &junos_rsvp_interface__descriptor },
    {    47, JTI_TREE_BOTH, "junos_task_memory", &junos_task_memory__descriptor },
    {    49, JTI_TREE_BOTH, "interfaces_l2al_interface", &interfaces_l2al_interface__descriptor },
    {    50, JTI_TREE_BOTH, "network_instances_l2_network_instance", &network_instances_l2_network_instance__descriptor },
    {    51, JTI_TREE_BOTH, "lldp_l2cp", &lldp_l2cp__descriptor },
    {    52, JTI_TREE_BOTH, "lacp_lacp", &lacp_lacp__descriptor },
    {    53, JTI_TREE_JTI, "arp_information_mib_arp", &arp_information_mib_arp__descriptor },
    {    53, JTI_TREE_EVO, "ldp_p2mp_lsp_branch_stats", &ldp_p2mp_lsp_branch_stats__descriptor },
    {    54, JTI_TREE_BOTH, "nd6_information_mib_nd6", &nd6_information_mib_nd6__descriptor },
    {    55, JTI_TREE_BOTH, "interfaces_mib", &interfaces_mib__descriptor },
    {    57, JTI_TREE_BOTH, "junos_pfe", &junos_pfe__descriptor },
    {    58, JTI_TREE_BOTH, "interfaces_pfe_ifl", &interfaces_pfe_ifl__descriptor },
    {    59, JTI_TREE_BOTH, "junos_pfe_npu", &junos_pfe_npu__descriptor },
    {    60, JTI_TREE_BOTH, "interfaces_pfe_port", &interfaces_pfe_port__descriptor },
    {    61, JTI_TREE_BOTH, "interfaces_local_interface", &interfaces_local_interface__descriptor },
    {    63, JTI_TREE_BOTH, "network_instances_bgp_rib", &network_instances_bgp_rib__descriptor },
    {    64, JTI_TREE_BOTH, "ipv6_ra_ipv6_ra", &ipv6_ra_ipv6_ra__descriptor },
    {    65, JTI_TREE_BOTH, "network_instances_isis", &network_instances_isis__descriptor },
    {    67, JTI_TREE_BOTH, "network_instances_ni_bgp", &network_instances_ni_bgp__descriptor },
    {    68, JTI_TREE_BOTH, "network_instances_rsvp", &network_instances_rsvp__descriptor },
    {    69, JTI_TREE_BOTH, "network_instances_te", &network_instances_te__descriptor },
    {    70, JTI_TREE_BOTH, "junos_smi", &junos_smi__descriptor },
    {    71, JTI_TREE_BOTH, "interfaces_vrrp", &interfaces_vrrp__descriptor },
    {    72, JTI_TREE_BOTH, "junos_kernel_ifstate", &junos_kernel_ifstate__descriptor },
    {    85, JTI_TREE_BOTH, "junos_kernel_health", &junos_kernel_health__descriptor },
    {    88, JTI_TREE_BOTH, "transceiver", &transceiver_data__descriptor },
    {    99, JTI_TREE_EVO, "interfaces_mgmt", &interfaces_mgmt__descriptor },
    {   104, JTI_TREE_BOTH, "mpls_SrTePerLspTransitStats", &mpls__sr_te_per_lsp_transit_stats__descriptor },
    {   105, JTI_TREE_BOTH, "mpls_SrTePerLspIngressStats", &mpls__sr_te_per_lsp_ingress_stats__descriptor },
    {   106, JTI_TREE_BOTH, "system_debug", &system_debug__descriptor },
    {   107, JTI_TREE_BOTH, "components_debug", &components_debug__descriptor },
    {   108, JTI_TREE_BOTH, "system_license", &system_license__descriptor },
    {   111, JTI_TREE_BOTH, "system_alarm", &system_alarm__descriptor },
    {   117, JTI_TREE_BOTH, "network_instances", &network_instances__descriptor },
    {   124, JTI_TREE_EVO, "junos_telemetry", &junos_telemetry__descriptor },
    {   126, JTI_TREE_BOTH, "ddos_stats", &ddos_stats__descriptor },
    {   129, JTI_TREE_BOTH, "junos_pfe_export_mon_stats", &junos_pfe_export_mon_stats__descriptor },
    {   130, JTI_TREE_BOTH, "junos_pfe_spu_cpu", &junos_pfe_spu_cpu__descriptor },
    {   131, JTI_TREE_BOTH, "junos_pfe_spu_flow", &junos_pfe_spu_flow__descriptor },
    {   132, JTI_TREE_BOTH, "network_instances_ldp", &network_instances_ldp__descriptor },
    {   133, JTI_TREE_BOTH, "interfaces_pfe_port_qstats", &interfaces_pfe_port_qstats__descriptor },
    {   134, JTI_TREE_BOTH, "qos", &qos__descriptor },
    {   135, JTI_TREE_BOTH, "interfaces_pfe_ifl_family_v4", &interfaces_pfe_ifl_family_v4__descriptor },
    {   136, JTI_TREE_BOTH, "interfaces_pfe_ifl_family_v6", &interfaces_pfe_ifl_family_v6__descriptor },
    {   139, JTI_TREE_BOTH, "junos_pfe_packet_capture", &junos_pfe_packet_capture__descriptor },
    {   142, JTI_TREE_EVO, "components_fab", &components_fab__descriptor },
    {   143, JTI_TREE_BOTH, "network_instances_pfe_per_prefix_v4", &network_instances_pfe_per_prefix_v4__descriptor },
    {   144, JTI_TREE_BOTH, "network_instances_pfe_per_prefix_v6", &network_instances_pfe_per_prefix_v6__descriptor },
    {   147, JTI_TREE_EVO, "components_telemetry", &components_telemetry__descriptor },
    {   153, JTI_TREE_BOTH, "ldp_lsp_ingress_stats", &ldp_lsp_ingress_stats__descriptor },
    {   154, JTI_TREE_BOTH, "ldp_lsp_transit_stats", &ldp_lsp_transit_stats__descriptor },
    {   155, JTI_TREE_BOTH, "ldp_p2mp_lsp_stats", &ldp_p2mp_lsp_stats__descriptor },
    {   156, JTI_TREE_BOTH, "ldp_p2mp_per_if_egress", &ldp_p2mp_per_if_egress__descriptor },
    {   157, JTI_TREE_BOTH, "ldp_p2mp_per_if_ingress", &ldp_p2mp_per_if_ingress__descriptor },
    {   162, JTI_TREE_EVO, "interfaces_mib_evolved", &interfaces_mib_evolved__descriptor },
    {   167, JTI_TREE_BOTH, "macsec_macsec", &macsec_macsec__descriptor },
    {   169, JTI_TREE_BOTH, "network_instances_SRTE", &network_instances__srte__descriptor },
    {   174, JTI_TREE_BOTH, "network_instances_pfe_mpls_sr_te_bsid", &network_instances_pfe_mpls_sr_te_bsid__descriptor },
    {   177, JTI_TREE_BOTH, "network_instances_pfe_mpls_sr_te_ip", &network_instances_pfe_mpls_sr_te_ip__descriptor },
    {   178, JTI_TREE_BOTH, "network_instances_pfe_mpls_sr_te_per_lsp_colored_ingress", &network_instances_pfe_mpls_sr_te_per_lsp_colored_ingress__descriptor },
    {   179, JTI_TREE_BOTH, "network_instances_pfe_mpls_sr_te_per_lsp_colored_transit", &network_instances_pfe_mpls_sr_te_per_lsp_colored_transit__descriptor },
    {   205, JTI_TREE_BOTH, "junos_saegw", &junos_saegw__descriptor },
    {   206, JTI_TREE_BOTH, "network_instances_PIM", &network_instances__pim__descriptor },
    {   210, JTI_TREE_BOTH, "system_health", &system_health__descriptor },
    {   211, JTI_TREE_BOTH, "telemetry_system_stats", &telemetry_system_stats__descriptor },
    {   212, JTI_TREE_EVO, "state_212", &state_212__descriptor },
    {   213, JTI_TREE_EVO, "system_telemetry_213", &system_telemetry_213__descriptor },
    {   215, JTI_TREE_EVO, "components_re_215", &components_re_215__descriptor },
    {   226, JTI_TREE_BOTH, "network_instances_ni_226", &network_instances_ni_226__descriptor },
    {   227, JTI_TREE_JTI, "qos_pfe_egress_qstats_227", &qos_pfe_egress_qstats__descriptor },
    {   227, JTI_TREE_EVO, "qos_pfe_egress_qstats", &qos_pfe_egress_qstats__descriptor },
    {   228, JTI_TREE_BOTH, "junos_228", &junos_228__descriptor },
    {   229, JTI_TREE_BOTH, "gribi_statistics_gribi_stats_229", &gribi_statistics_gribi_stats_229__descriptor },
    {   232, JTI_TREE_BOTH, "system_debug_232", &system_debug_232__descriptor },
    {   234, JTI_TREE_BOTH, "junos_pfe_iflset_234", &junos_pfe_iflset_234__descriptor },
    {   235, JTI_TREE_EVO, "state_235", &state_235__descriptor },
    {   236, JTI_TREE_EVO, "state_236", &state_236__descriptor },
    {   238, JTI_TREE_BOTH, "state_mist_238", &state_mist_238__descriptor },
    {   240, JTI_TREE_EVO, "components_fpc_240", &components_fpc_240__descriptor },
    {   242, JTI_TREE_BOTH, "bfd_242", &bfd_242__descriptor },
    {   243, JTI_TREE_BOTH, "junos_pfe_slice_egr_qstats_243", &junos_pfe_slice_egr_qstats_243__descriptor },
    {   244, JTI_TREE_BOTH, "qos_pfe_ingress_qstats_244", &qos_pfe_ingress_qstats_244__descriptor },
    {   246, JTI_TREE_BOTH, "state_chassis_246", &state_chassis_246__descriptor },
    {   247, JTI_TREE_BOTH, "network_instances_OSPFV2_247", &network_instances__ospfv2_247__descriptor },
    {   248, JTI_TREE_BOTH, "state_chassis_248", &state_chassis_248__descriptor },
    {   249, JTI_TREE_BOTH, "state_mib_249", &state_mib_249__descriptor },
    {   251, JTI_TREE_EVO, "acl_fwstatsd_evolved_251", &acl_fwstatsd_evolved_251__descriptor },
    {   252, JTI_TREE_EVO, "network_instances_fwstatsd_evolved_ni_252", &network_instances_fwstatsd_evolved_ni_252__descriptor },
    {   253, JTI_TREE_EVO, "sampling_253", &sampling_253__descriptor },
    {   254, JTI_TREE_EVO, "junos_254", &junos_254__descriptor },
    {   259, JTI_TREE_BOTH, "system_259", &system_259__descriptor },
    {   260, JTI_TREE_EVO, "system_260", &system_260__descriptor },
    {   261, JTI_TREE_BOTH, "interfaces_pnac_261", &interfaces_pnac_261__descriptor },
    {   262, JTI_TREE_BOTH, "network_instances_IGMP_262", &network_instances__igmp_262__descriptor },
    {   263, JTI_TREE_BOTH, "network_instances_evpn_263", &network_instances_evpn_263__descriptor },
    {   266, JTI_TREE_BOTH, "system_debug_266", &system_debug_266__descriptor },
    {   267, JTI_TREE_BOTH, "system_debug_267", &system_debug_267__descriptor },
    {   268, JTI_TREE_BOTH, "state_dot1x_268", &state_dot1x_268__descriptor },
    {   269, JTI_TREE_BOTH, "stp_stp_269", &stp_stp_269__descriptor },
    {   272, JTI_TREE_EVO, "junos_smi_272", &junos_smi_272__descriptor },
    {   273, JTI_TREE_EVO, "junos_pppoe_stats_273", &junos_pppoe_stats_273__descriptor },
    {   274, JTI_TREE_EVO, "junos_authentication_274", &junos_authentication_274__descriptor },
    {   276, JTI_TREE_EVO, "junos_l2tp_276", &junos_l2tp_276__descriptor },
    {   277, JTI_TREE_EVO, "junos_ppp_277", &junos_ppp_277__descriptor },
    {   278, JTI_TREE_BOTH, "state_events_278", &state_events_278__descriptor },
    {   279, JTI_TREE_EVO, "state_279", &state_279__descriptor },
    {   280, JTI_TREE_BOTH, "components_pipeline_counters_packet_280", &components_pipeline_counters_packet_280__descriptor },
    {   281, JTI_TREE_BOTH, "components_pipeline_counters_drop_281", &components_pipeline_counters_drop_281__descriptor },
    {   282, JTI_TREE_BOTH, "state_dhcp_security_282", &state_dhcp_security_282__descriptor },
    {   283, JTI_TREE_BOTH, "routing_policy_policy_283", &routing_policy_policy_283__descriptor },
    {   285, JTI_TREE_BOTH, "state_commit_history_285", &state_commit_history_285__descriptor },
    {   286, JTI_TREE_BOTH, "state_stats_286", &state_stats_286__descriptor },
    {   288, JTI_TREE_EVO, "state_mib2d_native_288", &state_mib2d_native_288__descriptor },
    {   290, JTI_TREE_BOTH, "state_bgp_state_290", &state_bgp_state_290__descriptor },
    {   291, JTI_TREE_BOTH, "state_bgp_rv_291", &state_bgp_rv_291__descriptor },
    {   293, JTI_TREE_EVO, "state_telemetry_293", &state_telemetry_293__descriptor },
    {   296, JTI_TREE_EVO, "state_fabric_path_296", &state_fabric_path_296__descriptor },
    {   297, JTI_TREE_EVO, "state_fpc_297", &state_fpc_297__descriptor },
    {   298, JTI_TREE_BOTH, "components_queueing_block_packet_298", &components_queueing_block_packet_298__descriptor },
    {   299, JTI_TREE_BOTH, "components_queueing_block_drop_299", &components_queueing_block_drop_299__descriptor },
    {   300, JTI_TREE_BOTH, "state_300", &state_300__descriptor },
    {   303, JTI_TREE_BOTH, "state_evpn_303", &state_evpn_303__descriptor },
    {   304, JTI_TREE_BOTH, "state_routing_tables_state_304", &state_routing_tables_state_304__descriptor },
    {   305, JTI_TREE_BOTH, "interfaces_if_ipv6_ra_305", &interfaces_if_ipv6_ra_305__descriptor },
    {   306, JTI_TREE_BOTH, "state_l2_learning_306", &state_l2_learning_306__descriptor },
    {   307, JTI_TREE_EVO, "state_307", &state_307__descriptor },
    {   308, JTI_TREE_EVO, "state_308", &state_308__descriptor },
    {   309, JTI_TREE_EVO, "state_alarmd_native_fpm_309", &state_alarmd_native_fpm_309__descriptor },
    {   310, JTI_TREE_EVO, "state_fabspoked_sib_310", &state_fabspoked_sib_310__descriptor },
    {   312, JTI_TREE_BOTH, "junos_subscribers_312", &junos_subscribers_312__descriptor },
    {   314, JTI_TREE_BOTH, "junos_smi_vc_314", &junos_smi_vc_314__descriptor },
    {   315, JTI_TREE_BOTH, "state_static_routing_state_315", &state_static_routing_state_315__descriptor },
    {   318, JTI_TREE_EVO, "network_instances_318", &network_instances_318__descriptor },
    {   319, JTI_TREE_EVO, "system_319", &system_319__descriptor },
    {   321, JTI_TREE_EVO, "network_instances_fwstatsd_evolved_ni_afts_321", &network_instances_fwstatsd_evolved_ni_afts_321__descriptor },
    {   322, JTI_TREE_BOTH, "state_srv6_state_322", &state_srv6_state_322__descriptor },
    {   324, JTI_TREE_BOTH, "state_pfe_srv6_324", &state_pfe_srv6_324__descriptor },
    {   325, JTI_TREE_BOTH, "state_pfe_srv6_srte_325", &state_pfe_srv6_srte_325__descriptor },
    {   326, JTI_TREE_BOTH, "state_pfe_srv6_col_per_path_ingress_326", &state_pfe_srv6_col_per_path_ingress_326__descriptor },
    {   327, JTI_TREE_BOTH, "state_pfe_srv6_srte_uncolored_per_tun_ingress_327", &state_pfe_srv6_srte_uncolored_per_tun_ingress_327__descriptor },
    {   328, JTI_TREE_BOTH, "state_pfe_srv6_uncol_per_path_ingress_328", &state_pfe_srv6_uncol_per_path_ingress_328__descriptor },
    {   331, JTI_TREE_EVO, "state_331", &state_331__descriptor },
    {   333, JTI_TREE_EVO, "components_re_333", &components_re_333__descriptor },
    {   335, JTI_TREE_EVO, "defined_sets_fwstatsd_evolved_df_sets_335", &defined_sets_fwstatsd_evolved_df_sets_335__descriptor },
    {   337, JTI_TREE_BOTH, "state_soft_gre_337", &state_soft_gre_337__descriptor },
    {   341, JTI_TREE_EVO, "system_341", &system_341__descriptor },
    {   347, JTI_TREE_BOTH, "diagnostics_bgp_diagnostics_347", &diagnostics_bgp_diagnostics_347__descriptor },
};

const int jti_dispatch_size = 186;

const jti_dispatch_entry_t *jti_dispatch_lookup(uint32_t ext_num)
{
    /* Linear scan — table is small enough; could binary-search if needed */
    for (int i = 0; i < jti_dispatch_size; i++) {
        if (jti_dispatch[i].ext_num == ext_num)
            return &jti_dispatch[i];
    }
    return NULL;
}
